/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmstrial.PersonnelFrames;

import dbmstrial.ConnectTESTING;
import static dbmstrial.MessgeRequest.removeButton;
import java.awt.Component;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Josh
 */
public class PR1 extends javax.swing.JPanel {
Connection conn = null;
ResultSet rs = null;
PreparedStatement ps = null;
    /**
     * Creates new form PR1
     */
    public PR1() {
        initComponents();
        removeButton(cmb_type);
        removeButton(cmb_description);
        removeButton(cmb_unitNum);
         try{
            conn = ConnectTESTING.Connect();
            String str3 = "select pe_type  from pfmo.propequip group by pe_type;";
            ps = conn.prepareStatement(str3);
            rs = ps.executeQuery();
            while(rs.next()){
                cmb_type.addItem(rs.getString("pe_type"));
            } 
            String str = "select deptofc_code from pfmo.dept_ofc";
            ps = conn.prepareStatement(str);
            rs = ps.executeQuery();
            while(rs.next()){
                cmb_office.addItem(rs.getString("deptofc_code"));
            } 
        }
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public static void removeButton(Container container){
        Component[] components = container.getComponents();
        for (Component component : components){
            if(component instanceof AbstractButton){
                container.remove(component);
            }
        }
    }
    
    public String getDateTime(){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_office = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox<>();
        cmb_description = new javax.swing.JComboBox<>();
        cmb_unitNum = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_natureRequest = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Creation of Service Request Form for Trouble Call");

        jLabel2.setText("Office/Department:");

        jLabel3.setText("Property Equipment");

        jLabel4.setText("Type:");

        jLabel5.setText("Description:");

        jLabel6.setText("Unit Number:");

        cmb_description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_descriptionMouseClicked(evt);
            }
        });

        cmb_unitNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_unitNumMouseClicked(evt);
            }
        });

        jLabel7.setText("Nature of Request");

        btn_submit.setText("Submit");
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_natureRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_submit))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_office, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmb_unitNum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmb_description, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_office, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_unitNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_natureRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_submit)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_descriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_descriptionMouseClicked
        cmb_description.removeAllItems();
        try{
            conn = ConnectTESTING.Connect();
            String str3 = "select pe_desc  from pfmo.propequip"
                    + " where pe_type = '"+cmb_type.getSelectedItem()+"'; ";
            ps = conn.prepareStatement(str3);
            rs = ps.executeQuery();
            while(rs.next()){
                cmb_description.addItem(rs.getString("pe_desc"));
            } 
        }
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_cmb_descriptionMouseClicked

    private void cmb_unitNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_unitNumMouseClicked
         cmb_unitNum.removeAllItems();
        try{
            conn = ConnectTESTING.Connect();
            String str3 = "select pu.pe_unit_no  from pfmo.propequip_unit pu "
                    + "inner join pfmo.propequip pr "
                    + "on pu.pe_code = pr.pe_code "
                    + "where pr.pe_desc = '"+cmb_description.getSelectedItem()+"'; ";
            ps = conn.prepareStatement(str3);
            rs = ps.executeQuery();
            while(rs.next()){
                cmb_unitNum.addItem(rs.getString("pu.pe_unit_no"));
            } 
        }
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_cmb_unitNumMouseClicked

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        int response = JOptionPane.showConfirmDialog(this,"Do you want to send this request?",
                  "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            try{
                String req_id = null;
                String str1 = "select req_id from pfmo.requestor "
                        + "where deptofc_code = '"+cmb_office.getSelectedItem()+"'; ";
                 ps = conn.prepareStatement(str1);
                 rs = ps.executeQuery();
                 if (rs.next()) req_id = rs.getString("req_id");
             
                conn = ConnectTESTING.Connect();
                String str = "insert into pfmo.service_request\n" +
                "(     sr_date\n" +
                "	, req_id \n" +
                "	, pe_unit_no \n" +
                "	, nature_request \n" +
                "	, status_code \n" +
                "	, rt_code \n" +
                "	, rec_code \n" +
                "	, target_date \n" +
                "	, section_code\n" +
                "	, emp_no \n" +
                "	, wstarted_date \n" +
                "	, wcomp_date \n" +
                "	, remarks, repair_cost , active )  values "
                        +" ('"+getDateTime()+"', "
                        +" '"+req_id+"', "
                        +"'"+cmb_unitNum.getSelectedItem()+"', "
                        +"'"+txt_natureRequest.getText().toString().trim()+"','O',null,null,null,null,null,null,null,null,null,'0'); ";
                ps = conn.prepareStatement(str);
                ps.execute();
              JOptionPane.showMessageDialog(null,"Submitting request was successful");
            } catch (Exception e){
               JOptionPane.showMessageDialog(null, e);
            }
        } else JOptionPane.showMessageDialog(null, "Submitting request cancelled");
    }//GEN-LAST:event_btn_submitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cmb_description;
    private javax.swing.JComboBox<String> cmb_office;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JComboBox<String> cmb_unitNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_natureRequest;
    // End of variables declaration//GEN-END:variables
}
