/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dbmstrial;

/**
 *
 * @author Christine Abbie
 */
public class A3 extends javax.swing.JFrame {

    /**
     * Creates new form SE2
     */
    public A3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        USRlbl = new javax.swing.JLabel();
        ViewBylbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BackMenubtn = new javax.swing.JButton();
        BackMenubtn1 = new javax.swing.JButton();
        BackMenubtn2 = new javax.swing.JButton();
        ViewBylbl1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        ViewBylbl3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1427, 724));
        getContentPane().setLayout(null);

        USRlbl.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        USRlbl.setText("List of Materials");
        getContentPane().add(USRlbl);
        USRlbl.setBounds(560, 160, 113, 19);

        ViewBylbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ViewBylbl.setText("Material Type:");
        getContentPane().add(ViewBylbl);
        ViewBylbl.setBounds(470, 200, 81, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(560, 190, 141, 20);

        BackMenubtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        BackMenubtn.setText("Add");
        BackMenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMenubtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackMenubtn);
        BackMenubtn.setBounds(470, 300, 86, 27);

        BackMenubtn1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        BackMenubtn1.setText("Edit");
        BackMenubtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMenubtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(BackMenubtn1);
        BackMenubtn1.setBounds(560, 300, 86, 27);

        BackMenubtn2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        BackMenubtn2.setText("Delete");
        BackMenubtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMenubtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(BackMenubtn2);
        BackMenubtn2.setBounds(650, 300, 86, 27);

        ViewBylbl1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ViewBylbl1.setText("Description:");
        getContentPane().add(ViewBylbl1);
        ViewBylbl1.setBounds(480, 220, 68, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(560, 220, 141, 20);

        ViewBylbl3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ViewBylbl3.setText("Code:");
        getContentPane().add(ViewBylbl3);
        ViewBylbl3.setBounds(510, 250, 32, 17);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(560, 250, 141, 20);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material Code", "Description", "Quantity", "Date Purchased"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 360, 862, 187);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG IN.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMenubtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMenubtnActionPerformed

    private void BackMenubtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMenubtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMenubtn1ActionPerformed

    private void BackMenubtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMenubtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMenubtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackMenubtn;
    private javax.swing.JButton BackMenubtn1;
    private javax.swing.JButton BackMenubtn2;
    private javax.swing.JLabel USRlbl;
    private javax.swing.JLabel ViewBylbl;
    private javax.swing.JLabel ViewBylbl1;
    private javax.swing.JLabel ViewBylbl3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
