/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmstrial;

import chief.C3;
import chief.C4;
import chief.Chief2;
import chief.chief1;
import chief.chief1pt1;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author Josh
 */
public class Chief extends javax.swing.JFrame {
GridBagLayout layout = new GridBagLayout();
chief1 chief1;
chief1pt1 chief1pt1;
Chief2 chief2;
C3 c3;
C4 c4;
    /**
     * Creates new form Chief
     */
    public Chief() {
        initComponents();
        chief1 = new chief1();
        chief1pt1 = new chief1pt1();
        chief2 = new Chief2();
        c3 = new C3();
        c4 = new C4();
        ChiefPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        ChiefPanel.add(chief1,c);
        ChiefPanel.add(chief1pt1,c);
        ChiefPanel.add(chief2,c);
        ChiefPanel.add(c3,c);
        ChiefPanel.add(c4,c);
        chief1.setVisible(true);
        chief1pt1.setVisible(false);
        chief2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_srForm = new javax.swing.JButton();
        btn_srRecord = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        ChiefPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1427, 724));
        getContentPane().setLayout(null);

        btn_srForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/1.jpg"))); // NOI18N
        btn_srForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_srFormMouseClicked(evt);
            }
        });
        getContentPane().add(btn_srForm);
        btn_srForm.setBounds(40, 240, 184, 20);

        btn_srRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/2.jpg"))); // NOI18N
        btn_srRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_srRecordMouseClicked(evt);
            }
        });
        getContentPane().add(btn_srRecord);
        btn_srRecord.setBounds(40, 270, 184, 20);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOGOUT.jpg"))); // NOI18N
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout);
        btn_logout.setBounds(40, 470, 184, 20);

        ChiefPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ChiefPanelLayout = new javax.swing.GroupLayout(ChiefPanel);
        ChiefPanel.setLayout(ChiefPanelLayout);
        ChiefPanelLayout.setHorizontalGroup(
            ChiefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        ChiefPanelLayout.setVerticalGroup(
            ChiefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        getContentPane().add(ChiefPanel);
        ChiefPanel.setBounds(250, 210, 612, 392);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG IN.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_srFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srFormMouseClicked
        // TODO add your handling code here:
        chief1.setVisible(true);
        chief1pt1.setVisible(false);
        chief2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
    }//GEN-LAST:event_btn_srFormMouseClicked

    private void btn_srRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_srRecordMouseClicked
        // TODO add your handling code here:
        chief2.setVisible(true);
        chief1.setVisible(false);
        chief1pt1.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
    }//GEN-LAST:event_btn_srRecordMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        LogInScreen login = new LogInScreen();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chief.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chief().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ChiefPanel;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_srForm;
    private javax.swing.JButton btn_srRecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
