/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmstrial;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Josh
 */
public class LogInScreen extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement ps = null;
    /**
     * Creates new form LogInScreen
     */
    public LogInScreen() {
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        initComponents();
        lbl_Pop.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Username = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        txt_Username = new javax.swing.JTextField();
        Btn_LogIn = new javax.swing.JButton();
        lbl_Pop = new javax.swing.JLabel();
        lbl_Username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1427, 724));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        lbl_Username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Username.setText("LOG-IN");
        getContentPane().add(lbl_Username);
        lbl_Username.setBounds(590, 190, 70, 30);

        lbl_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Password.setText("Password:");
        getContentPane().add(lbl_Password);
        lbl_Password.setBounds(440, 270, 190, 14);

        txt_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Password);
        txt_Password.setBounds(540, 270, 180, 20);

        txt_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_Username);
        txt_Username.setBounds(540, 240, 180, 20);

        Btn_LogIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG-IN.jpg"))); // NOI18N
        Btn_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_LogInMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_LogIn);
        Btn_LogIn.setBounds(550, 330, 160, 23);

        lbl_Pop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_Pop.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Pop.setText("Wrong Username or Password!");
        getContentPane().add(lbl_Pop);
        lbl_Pop.setBounds(540, 290, 180, 30);

        lbl_Username1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Username1.setText("Username:");
        getContentPane().add(lbl_Username1);
        lbl_Username1.setBounds(440, 240, 190, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG IN.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_LogInMouseClicked
        // TODO add your handling code here:
        try{
        conn = ConnectTESTING.Connect();
        String str = "Select username, password, access_code from pfmo.user_account" +
                " where username = '"+txt_Username.getText().toString().trim()+"' and " +
                " password = '"+txt_Password.getText().toString().trim()+"'";
        ps = conn.prepareStatement(str);
        rs = ps.executeQuery();
        Stakeholder stake = new Stakeholder();
        SectionHead sh = new SectionHead();
        /* Checks if user exist */
        if(rs.next()){
             String str2 = rs.getString("access_code");
            if(str2.equals("0005")){
                 stake.username = txt_Username.getText().toString().trim();
                 stake.setVisible(true); 
                 this.dispose();}
            else if (str2.equals("0001")){
                Chief ch = new Chief();
                ch.setVisible(true);
                this.dispose();
            } else if (str2.equals("0002")){
                Personnel1 pe = new Personnel1();
                pe.setVisible(true);
                this.dispose();
            } else if (str2.equals("0003")){
                 sh.username = txt_Username.getText().toString().trim();
                sh.setVisible(true);
                this.dispose();
            }else if (str2.equals("0004")){
                Storekeeper sk = new Storekeeper();
                sk.setVisible(true);
                this.dispose();
            }else if (str2.equals("0000")){
                Admin a = new Admin();
                a.setVisible(true);
                this.dispose();
            }
            
        else lbl_Pop.setVisible(true);
        }}
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_Btn_LogInMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         conn = ConnectTESTING.Connect();
    }//GEN-LAST:event_formWindowActivated

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
           try{
        conn = ConnectTESTING.Connect();
        String str = "Select username, password, access_code from pfmo.user_account" +
                " where username = '"+txt_Username.getText().toString().trim()+"' and " +
                " password = '"+txt_Password.getText().toString().trim()+"'";
        ps = conn.prepareStatement(str);
        rs = ps.executeQuery();
        Stakeholder stake = new Stakeholder();
        SectionHead sh = new SectionHead();
        if(rs.next()){
             String str2 = rs.getString("access_code");
            if(str2.equals("0005")){
                 stake.username = txt_Username.getText().toString().trim();
                 stake.setVisible(true); 
                 this.dispose();}
            else if (str2.equals("0001")){
                Chief ch = new Chief();
                ch.setVisible(true);
                this.dispose();
            } else if (str2.equals("0002")){
                Personnel1 pe = new Personnel1();
                pe.setVisible(true);
                this.dispose();
            } else if (str2.equals("0003")){
                 sh.username = txt_Username.getText().toString().trim();
                sh.setVisible(true);
                this.dispose();
            }else if (str2.equals("0004")){
                Storekeeper sk = new Storekeeper();
                sk.setVisible(true);
                this.dispose();
            } 
        else lbl_Pop.setVisible(true);
        }}
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        } 
    }//GEN-LAST:event_txt_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Pop;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_Username1;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
