/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmstrial;

import java.awt.Component;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.AbstractButton;


/**
 *
 * @author Josh
 */
public class MessgeRequest extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement ps = null;
    /**
     * Creates new form MessgeRequest
     */
    public MessgeRequest() {
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        initComponents();
        removeButton(cmb_type);
        removeButton(cmb_description);
        removeButton(cmb_unitNum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbl_lastName = new javax.swing.JLabel();
        lbl_firstName = new javax.swing.JLabel();
        lbl_middleName = new javax.swing.JLabel();
        lbl_propEquip = new javax.swing.JLabel();
        cmb_type = new javax.swing.JComboBox<>();
        cmb_description = new javax.swing.JComboBox<>();
        cmb_unitNum = new javax.swing.JComboBox<>();
        txt_natureRequest = new javax.swing.JTextField();
        lbl_middleName1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1427, 724));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(905, 490, 210, 30);

        lbl_lastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_lastName.setText("Type:");
        getContentPane().add(lbl_lastName);
        lbl_lastName.setBounds(290, 230, 45, 22);

        lbl_firstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_firstName.setText("Description:");
        getContentPane().add(lbl_firstName);
        lbl_firstName.setBounds(240, 260, 110, 30);

        lbl_middleName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_middleName.setText("Nature of Request:");
        getContentPane().add(lbl_middleName);
        lbl_middleName.setBounds(180, 350, 170, 22);

        lbl_propEquip.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_propEquip.setText("Property Equipment");
        getContentPane().add(lbl_propEquip);
        lbl_propEquip.setBounds(360, 180, 200, 30);

        cmb_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_typeMouseClicked(evt);
            }
        });
        cmb_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_type);
        cmb_type.setBounds(350, 220, 240, 30);

        cmb_description.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_descriptionMouseClicked(evt);
            }
        });
        cmb_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_descriptionActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_description);
        cmb_description.setBounds(350, 260, 240, 28);

        cmb_unitNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_unitNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_unitNumMouseClicked(evt);
            }
        });
        getContentPane().add(cmb_unitNum);
        cmb_unitNum.setBounds(350, 300, 240, 28);

        txt_natureRequest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_natureRequest);
        txt_natureRequest.setBounds(350, 350, 770, 100);

        lbl_middleName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_middleName1.setText("Unit No.:");
        getContentPane().add(lbl_middleName1);
        lbl_middleName1.setBounds(260, 300, 90, 22);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 490, 180, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG IN.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1390, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try{
            conn = ConnectTESTING.Connect();
            String str3 = "select pe_type  from pfmo.propequip group by pe_type;";
            ps = conn.prepareStatement(str3);
            rs = ps.executeQuery();
            while(rs.next()){
                cmb_type.addItem(rs.getString("pe_type"));
            } 
        }
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,"Do you want to send this request?",
                  "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            try{
                Stakeholder st = new Stakeholder();
             
                conn = ConnectTESTING.Connect();
                String str = "insert into pfmo.service_request\n" +
                "(     sr_date\n" +
                "	, req_id \n" +
                "	, pe_unit_no \n" +
                "	, nature_request \n" +
                "	, status_code \n" +
                "	, rt_code \n" +
                "	, rec_code \n" +
                "	, target_date \n" +
                "	, section_code\n" +
                "	, emp_no \n" +
                "	, wstarted_date \n" +
                "	, wcomp_date \n" +
                "	, remarks, repair_cost , active )  values "
                        +" ('"+getDateTime()+"', "
                        +" '"+st.cdo+"', "
                        +"'"+cmb_unitNum.getSelectedItem()+"', "
                        +"'"+txt_natureRequest.getText().toString().trim()+"','O',null,null,null,null,null,null,null,null,null,'0'); ";
                ps = conn.prepareStatement(str);
                ps.execute();
              JOptionPane.showMessageDialog(null,"Submitting request was successful");
                this.dispose();
            } catch (Exception e){
               JOptionPane.showMessageDialog(null, e);
            }
        } else JOptionPane.showMessageDialog(null, "Submitting request cancelled");
    }//GEN-LAST:event_jButton1MouseClicked

    private void cmb_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_typeMouseClicked

    }//GEN-LAST:event_cmb_typeMouseClicked

    private void cmb_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_typeActionPerformed

    private void cmb_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_descriptionActionPerformed

    }//GEN-LAST:event_cmb_descriptionActionPerformed

    private void cmb_descriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_descriptionMouseClicked
        // TODO add your handling code here:
        cmb_description.removeAllItems();
        try{
            conn = ConnectTESTING.Connect();
            String str3 = "select pe_desc  from pfmo.propequip"
                    + " where pe_type = '"+cmb_type.getSelectedItem()+"'; ";
            ps = conn.prepareStatement(str3);
            rs = ps.executeQuery();
            while(rs.next()){
                cmb_description.addItem(rs.getString("pe_desc"));
            } 
        }
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_cmb_descriptionMouseClicked

    private void cmb_unitNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_unitNumMouseClicked
         cmb_unitNum.removeAllItems();
        try{
            conn = ConnectTESTING.Connect();
            String str3 = "select pu.pe_unit_no  from pfmo.propequip_unit pu "
                    + "inner join pfmo.propequip pr "
                    + "on pu.pe_code = pr.pe_code "
                    + "where pr.pe_desc = '"+cmb_description.getSelectedItem()+"'; ";
            ps = conn.prepareStatement(str3);
            rs = ps.executeQuery();
            while(rs.next()){
                cmb_unitNum.addItem(rs.getString("pu.pe_unit_no"));
            } 
        }
        catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_cmb_unitNumMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    public String getDateTime(){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = new Date();
        return dateFormat.format(date);            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessgeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessgeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessgeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessgeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessgeRequest().setVisible(true);
            }
        });
    }
    
    public static void removeButton(Container container){
        Component[] components = container.getComponents();
        for (Component component : components){
            if(component instanceof AbstractButton){
                container.remove(component);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_description;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JComboBox<String> cmb_unitNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_middleName;
    private javax.swing.JLabel lbl_middleName1;
    private javax.swing.JLabel lbl_propEquip;
    private javax.swing.JTextField txt_natureRequest;
    // End of variables declaration//GEN-END:variables
}
