/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmstrial;

import sectionhead.SH1;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;
import sectionhead.SH1T;
import sectionhead.SH2;
import sectionhead.SH3;
import sectionhead.SH4;
import sectionhead.SH6;
import sectionhead.SH7;

/**
 *
 * @author Josh
 */
public class SectionHead extends javax.swing.JFrame {
public static String username;
GridBagLayout layout = new GridBagLayout();
SH1 s1;
SH2 s2;
SH3 s3;
SH4 s4;
SH6 s6;
SH1T s1t;

    /**
     * Creates new form SectionHead
     */
    public SectionHead() {
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        initComponents();
        s1 = new SH1();
        s2 = new SH2();
        s3 = new SH3();
        s4 = new SH4();
        s6 = new SH6();
        s1t = new SH1T();
        SHPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        SHPanel.add(s1,c);
        SHPanel.add(s2,c);
        SHPanel.add(s3,c);
        SHPanel.add(s4,c);
        SHPanel.add(s6,c);
        s1.setVisible(false);
        s2.setVisible(false);
        s3.setVisible(false);
        s4.setVisible(false);
        s6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btn_ServiceReq = new javax.swing.JButton();
        SHPanel = new javax.swing.JPanel();
        btn_WorkOrder = new javax.swing.JButton();
        btn_InventTools = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1427, 724));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_ServiceReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SE1.jpg"))); // NOI18N
        btn_ServiceReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ServiceReqMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ServiceReq);
        btn_ServiceReq.setBounds(50, 250, 210, 20);

        SHPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SHPanelLayout = new javax.swing.GroupLayout(SHPanel);
        SHPanel.setLayout(SHPanelLayout);
        SHPanelLayout.setHorizontalGroup(
            SHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        SHPanelLayout.setVerticalGroup(
            SHPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(SHPanel);
        SHPanel.setBounds(300, 190, 1020, 450);

        btn_WorkOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SE2.jpg"))); // NOI18N
        btn_WorkOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_WorkOrderMouseClicked(evt);
            }
        });
        getContentPane().add(btn_WorkOrder);
        btn_WorkOrder.setBounds(50, 280, 210, 20);

        btn_InventTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SE6.jpg"))); // NOI18N
        btn_InventTools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_InventToolsMouseClicked(evt);
            }
        });
        getContentPane().add(btn_InventTools);
        btn_InventTools.setBounds(50, 310, 210, 20);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LO.jpg"))); // NOI18N
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout);
        btn_logout.setBounds(50, 370, 210, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG IN.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1390, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // Log Out
         LogInScreen login = new LogInScreen();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_WorkOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_WorkOrderMouseClicked
        s1.setVisible(false);
        s2.setVisible(true);
        s3.setVisible(false);
        s4.setVisible(false);
        s6.setVisible(false);
    }//GEN-LAST:event_btn_WorkOrderMouseClicked

    private void btn_ServiceReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ServiceReqMouseClicked
        s1t.username = username;
        s1t.setVisible(true);
    }//GEN-LAST:event_btn_ServiceReqMouseClicked

    private void btn_InventToolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InventToolsMouseClicked
        s1.setVisible(false);
        s2.setVisible(false);
        s3.setVisible(false);
        s4.setVisible(false);
        s6.setVisible(true);

    }//GEN-LAST:event_btn_InventToolsMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated
 
    public String someMethod(){
        return username;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SectionHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SectionHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SectionHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SectionHead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SectionHead().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SHPanel;
    private javax.swing.JButton btn_InventTools;
    private javax.swing.JButton btn_ServiceReq;
    private javax.swing.JButton btn_WorkOrder;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    // End of variables declaration//GEN-END:variables
}
