/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmstrial;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Josh
 */
public class Stakeholder extends javax.swing.JFrame {
    public String username = " ";
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    public static String cdo;

    /**
     * Creates new form Stakeholder
     */
    public Stakeholder() {
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_SubmitRequest1 = new javax.swing.JButton();
        btn_SubmitRequest = new javax.swing.JButton();
        btn_ViewRequest = new javax.swing.JButton();
        txt_Con = new javax.swing.JLabel();
        txt_Name = new javax.swing.JLabel();
        txt_DepName = new javax.swing.JLabel();
        txt_EmpID = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        lbl_Employee_Id = new javax.swing.JLabel();
        lbl_DeptName = new javax.swing.JLabel();
        lbl_Position = new javax.swing.JLabel();
        txt_ContactNumber = new javax.swing.JLabel();
        txt_Position1 = new javax.swing.JLabel();
        lbl_Name1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btn_SubmitRequest1.setText("Submit Request");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1427, 724));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_SubmitRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/S1.jpg"))); // NOI18N
        btn_SubmitRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SubmitRequestMouseClicked(evt);
            }
        });
        getContentPane().add(btn_SubmitRequest);
        btn_SubmitRequest.setBounds(470, 450, 220, 30);

        btn_ViewRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/S2.jpg"))); // NOI18N
        btn_ViewRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ViewRequestMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ViewRequest);
        btn_ViewRequest.setBounds(710, 450, 220, 30);

        txt_Con.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_Con);
        txt_Con.setBounds(570, 350, 510, 19);

        txt_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_Name);
        txt_Name.setBounds(580, 229, 480, 20);

        txt_DepName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_DepName);
        txt_DepName.setBounds(580, 289, 500, 20);

        txt_EmpID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_EmpID);
        txt_EmpID.setBounds(590, 259, 190, 20);

        lbl_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Name.setText("PROFILE");
        getContentPane().add(lbl_Name);
        lbl_Name.setBounds(620, 180, 150, 22);

        lbl_Employee_Id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Employee_Id.setText("Employee ID:");
        getContentPane().add(lbl_Employee_Id);
        lbl_Employee_Id.setBounds(460, 260, 107, 22);

        lbl_DeptName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DeptName.setText("Department Name:");
        getContentPane().add(lbl_DeptName);
        lbl_DeptName.setBounds(420, 290, 149, 22);

        lbl_Position.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Position.setText("Position:");
        getContentPane().add(lbl_Position);
        lbl_Position.setBounds(500, 320, 68, 22);

        txt_ContactNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_ContactNumber.setText("Contact Number:");
        getContentPane().add(txt_ContactNumber);
        txt_ContactNumber.setBounds(430, 350, 134, 22);

        txt_Position1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txt_Position1);
        txt_Position1.setBounds(580, 320, 490, 19);

        lbl_Name1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Name1.setText("Name:");
        getContentPane().add(lbl_Name1);
        lbl_Name1.setBounds(520, 230, 60, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 510, 200, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG IN.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SubmitRequestMouseClicked
        MessgeRequest mr = new MessgeRequest();
        mr.setVisible(true);
    }//GEN-LAST:event_btn_SubmitRequestMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try{
        conn = ConnectTESTING.Connect();
        String str = "select * from pfmo.req_info "+
          "where username = '"+username+"'; ";
        ps = conn.prepareStatement(str);
        rs = ps.executeQuery();
        while(rs.next()){
            txt_Name.setText(rs.getString("req_name"));
            txt_EmpID.setText(rs.getString("req_id"));
            txt_DepName.setText(rs.getString("deptofc_desc"));
            txt_Position1.setText(rs.getString("position_desc"));
            txt_Con.setText(rs.getString("contact_no"));
            cdo = rs.getString("req_id");
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        
    }//GEN-LAST:event_formWindowActivated

    private void btn_ViewRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewRequestMouseClicked
        // TODO add your handling code here:
        ViewRequest vr = new ViewRequest();
        vr.setVisible(true);
    }//GEN-LAST:event_btn_ViewRequestMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        LogInScreen log = new LogInScreen();
        log.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stakeholder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stakeholder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stakeholder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stakeholder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stakeholder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SubmitRequest;
    private javax.swing.JButton btn_SubmitRequest1;
    private javax.swing.JButton btn_ViewRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_DeptName;
    private javax.swing.JLabel lbl_Employee_Id;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Name1;
    private javax.swing.JLabel lbl_Position;
    private javax.swing.JLabel txt_Con;
    private javax.swing.JLabel txt_ContactNumber;
    private javax.swing.JLabel txt_DepName;
    private javax.swing.JLabel txt_EmpID;
    private javax.swing.JLabel txt_Name;
    private javax.swing.JLabel txt_Position1;
    // End of variables declaration//GEN-END:variables
}
