/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmstrial;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import storekeeper.SK1;
import storekeeper.SK12;
import storekeeper.SK13;
import storekeeper.SK16;
import storekeeper.SK17;
import storekeeper.SK21;
import storekeeper.SK22;
import storekeeper.SK23;
import storekeeper.SK24;

/**
 *
 * @author Josh
 */
public class Storekeeper extends javax.swing.JFrame {
GridBagLayout layout = new GridBagLayout();
SK1 sk11;
SK12 sk12;
SK13 sk13;
SK16 sk16;
SK17 sk17;
SK21 sk21;
SK22 sk22;
SK23 sk23;
SK24 sk24;
    /**
     * Creates new form Storekeeper
     */
    public Storekeeper() {
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        initComponents();
        sk11 = new SK1();
        sk12 = new SK12();
        sk13 = new SK13();
        sk16 = new SK16();
        sk17 = new SK17();
        sk21 = new SK21();
        sk22 = new SK22();
        sk23 = new SK23();
        sk24 = new SK24();
        SK_Panel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        SK_Panel.add(sk11,c);
        SK_Panel.add(sk12,c);
        SK_Panel.add(sk13,c);
        SK_Panel.add(sk16,c);
        SK_Panel.add(sk17,c);
        SK_Panel.add(sk21,c);
        SK_Panel.add(sk22,c);
        SK_Panel.add(sk23,c);
        SK_Panel.add(sk24,c);
        sk11.setVisible(true);
        sk12.setVisible(false);
        sk13.setVisible(false);
        sk16.setVisible(false);
        sk17.setVisible(false);
        sk21.setVisible(false);
        sk22.setVisible(false);
        sk23.setVisible(false);
        sk24.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SK_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_viewTools = new javax.swing.JButton();
        btn_addStock = new javax.swing.JButton();
        btn_replaceStock = new javax.swing.JButton();
        btn_inventory = new javax.swing.JButton();
        btn_borrowingTools = new javax.swing.JButton();
        btn_LogOut = new javax.swing.JButton();
        btn_UpdatingTools = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1427, 724));
        getContentPane().setLayout(null);

        SK_Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SK_PanelLayout = new javax.swing.GroupLayout(SK_Panel);
        SK_Panel.setLayout(SK_PanelLayout);
        SK_PanelLayout.setHorizontalGroup(
            SK_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        SK_PanelLayout.setVerticalGroup(
            SK_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(SK_Panel);
        SK_Panel.setBounds(300, 210, 1010, 470);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("INVENTORY OF TOOLS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 230, 190, 17);

        btn_viewTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SK1.jpg"))); // NOI18N
        btn_viewTools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewToolsMouseClicked(evt);
            }
        });
        getContentPane().add(btn_viewTools);
        btn_viewTools.setBounds(30, 260, 200, 20);

        btn_addStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SK2.jpg"))); // NOI18N
        btn_addStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addStockMouseClicked(evt);
            }
        });
        getContentPane().add(btn_addStock);
        btn_addStock.setBounds(30, 290, 200, 20);

        btn_replaceStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SK3.jpg"))); // NOI18N
        btn_replaceStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_replaceStockMouseClicked(evt);
            }
        });
        getContentPane().add(btn_replaceStock);
        btn_replaceStock.setBounds(30, 320, 200, 20);

        btn_inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SK4.jpg"))); // NOI18N
        getContentPane().add(btn_inventory);
        btn_inventory.setBounds(30, 350, 200, 20);

        btn_borrowingTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SK5.jpg"))); // NOI18N
        btn_borrowingTools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrowingToolsMouseClicked(evt);
            }
        });
        getContentPane().add(btn_borrowingTools);
        btn_borrowingTools.setBounds(30, 380, 200, 20);

        btn_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LO.jpg"))); // NOI18N
        btn_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogOutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_LogOut);
        btn_LogOut.setBounds(30, 470, 200, 20);

        btn_UpdatingTools.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/SK6.jpg"))); // NOI18N
        btn_UpdatingTools.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpdatingToolsMouseClicked(evt);
            }
        });
        getContentPane().add(btn_UpdatingTools);
        btn_UpdatingTools.setBounds(30, 410, 200, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIII/LOG IN.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1390, 724);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewToolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewToolsMouseClicked
        sk11.setVisible(true);
        sk12.setVisible(false);
        sk13.setVisible(false);
        sk16.setVisible(false);
        sk17.setVisible(false);
        sk21.setVisible(false);
        sk22.setVisible(false);
        sk23.setVisible(false);
        sk24.setVisible(false);
    }//GEN-LAST:event_btn_viewToolsMouseClicked

    private void btn_addStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addStockMouseClicked
        sk11.setVisible(false);
        sk12.setVisible(true);
        sk13.setVisible(false);
        sk16.setVisible(false);
        sk17.setVisible(false);
        sk21.setVisible(false);
        sk22.setVisible(false);
        sk23.setVisible(false);
        sk24.setVisible(false);
    }//GEN-LAST:event_btn_addStockMouseClicked

    private void btn_replaceStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_replaceStockMouseClicked
        sk11.setVisible(false);
        sk12.setVisible(false);
        sk13.setVisible(true);
        sk16.setVisible(false);
        sk17.setVisible(false);
        sk21.setVisible(false);
        sk22.setVisible(false);
        sk23.setVisible(false);
        sk24.setVisible(false);
    }//GEN-LAST:event_btn_replaceStockMouseClicked

    private void btn_borrowingToolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrowingToolsMouseClicked
        sk11.setVisible(false);
        sk12.setVisible(false);
        sk13.setVisible(false);
        sk16.setVisible(true);
        sk17.setVisible(false);
        sk21.setVisible(false);
        sk22.setVisible(false);
        sk23.setVisible(false);
        sk24.setVisible(false);
    }//GEN-LAST:event_btn_borrowingToolsMouseClicked

    private void btn_UpdatingToolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdatingToolsMouseClicked
        sk11.setVisible(false);
        sk12.setVisible(false);
        sk13.setVisible(false);
        sk16.setVisible(false);
        sk17.setVisible(true);
        sk21.setVisible(false);
        sk22.setVisible(false);
        sk23.setVisible(false);
        sk24.setVisible(false);
    }//GEN-LAST:event_btn_UpdatingToolsMouseClicked

    private void btn_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogOutMouseClicked
        // LOG OUT
        LogInScreen login = new LogInScreen();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_LogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Storekeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Storekeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Storekeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Storekeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Storekeeper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SK_Panel;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_UpdatingTools;
    private javax.swing.JButton btn_addStock;
    private javax.swing.JButton btn_borrowingTools;
    private javax.swing.JButton btn_inventory;
    private javax.swing.JButton btn_replaceStock;
    private javax.swing.JButton btn_viewTools;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    // End of variables declaration//GEN-END:variables
}
